export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FAIL = 'SIGN_IN_FAIL';
export const SIGN_OUT = 'SIGN_OUT';

export const RESET_AUTH_FORM = 'RESET_AUTH_FORM';

export const FETCH_RECOMMEND_MENTOR = 'FETCH_RECOMMEND_MENTOR';
export const FETCH_RECOMMEND_MENTOR_ERROR = 'FETCH_RECOMMEND_MENTOR_ERROR';

export const FETCH_RECOMMEND_MENTOR_BY_MAJOR = 'FETCH_RECOMMEND_MENTOR';
export const FETCH_RECOMMEND_MENTOR_BY_MAJOR_ERROR = 'FETCH_RECOMMEND_MENTOR_ERROR';

export const FETCH_MAJOR_ALL = 'FETCH_MAJOR_ALL';
export const FETCH_SUBJECT_BY_MAJOR = 'FETCH_SUBJECT_BY_MAJOR';

export const FETCH_MENTOR_SEARCH = 'FETCH_MENTOR_SEARCH';

export const FETCH_MENTOR_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_MENTOR_BY_ID_FAIL = 'FETCH_COURSE_BY_ID_FAIL';

export const FETCH_COURSE_SEARCH = 'FETCH_COURSE_SEARCH';
export const FETCH_MY_LEARNING_COURSES = 'FETCH_MY_LEARNING_COURSES';
export const FETCH_COURSE_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_COURSE_BY_ID_FAIL = 'FETCH_COURSE_BY_ID_FAIL';
export const FETCH_COURSES_BY_MENTOR_ID = 'FETCH_COURSES_BY_MENTOR_ID';
export const FETCH_RECOMMEND_COURSES_BY_MAJOR = 'FETCH_RECOMMEND_COURSES_BY_MAJOR';

export const TEST_ADD_COURSE = 'TEST_ADD_COURSE';
export const TEST_FETCH_COURSES = 'TEST_FETCH_COURSES';
export const TEST_DELETE_COURSE = 'TEST_DELETE_COURSE';
export const TEST_FETCH_COURSE = 'TEST_FETCH_COURSE';
export const TEST_UPDATE_COURSE = 'TEST_UPDATE_COURSE';

