export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FAIL = 'SIGN_IN_FAIL';
export const SIGN_OUT = 'SIGN_OUT';

export const RESET_AUTH_FORM = 'RESET_AUTH_FORM';

export const FETCH_RECOMMEND_MENTOR = 'FETCH_RECOMMEND_MENTOR';
export const FETCH_RECOMMEND_MENTOR_ERROR = 'FETCH_RECOMMEND_MENTOR_ERROR';

export const FETCH_RECOMMEND_MENTOR_BY_MAJOR = 'FETCH_RECOMMEND_MENTOR';
export const FETCH_RECOMMEND_MENTOR_BY_MAJOR_ERROR = 'FETCH_RECOMMEND_MENTOR_ERROR';