export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FAIL = 'SIGN_IN_FAIL';
export const SIGN_OUT = 'SIGN_OUT';

export const RESET_AUTH_FORM = 'RESET_AUTH_FORM';

//USER

export const FETCH_USER = 'FETCH_USER';

// MENTOR
export const FETCH_RECOMMEND_MENTOR = 'FETCH_RECOMMEND_MENTOR';
export const FETCH_RECOMMEND_MENTOR_ERROR = 'FETCH_RECOMMEND_MENTOR_ERROR';

export const FETCH_RECOMMEND_MENTOR_BY_MAJOR = 'FETCH_RECOMMEND_MENTOR_BY_MAJOR';
export const FETCH_RECOMMEND_MENTOR_BY_MAJOR_ERROR = 'FETCH_RECOMMEND_MENTOR_BY_MAJOR_ERROR';

export const FETCH_MAJOR_ALL = 'FETCH_MAJOR_ALL';

export const FETCH_MENTOR_MAJORS = 'FETCH_MENTOR_MAJORS';
export const FETCH_SUBJECT_BY_MAJOR = 'FETCH_SUBJECT_BY_MAJOR';

export const FETCH_MENTOR_SEARCH = 'FETCH_MENTOR_SEARCH';

export const FETCH_MENTOR_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_MENTOR_BY_ID_FAIL = 'FETCH_COURSE_BY_ID_FAIL';

export const UPDATE_MENTOR_PROFILE = 'UPDATE_MENTOR_PROFILE';
export const UPDATE_MENTOR_PROFILE_SUCCESS = 'UPDATE_MENTOR_PROFILE_SUCCESS';
export const UPDATE_MENTOR_PROFILE_FAIL = 'UPDATE_MENTOR_PROFILE_FAIL';

export const UPDATE_MENTOR_PROFILE_CLOSE_SNACKBAR = 'UPDATE_MENTOR_PROFILE_CLOSE_SNACKBAR';


// COURSE
export const FETCH_COURSE_SEARCH = 'FETCH_COURSE_SEARCH';

export const FETCH_COURSE_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_COURSE_BY_ID_FAIL = 'FETCH_COURSE_BY_ID_FAIL';
export const FETCH_COURSES_BY_MENTOR_ID = 'FETCH_COURSES_BY_MENTOR_ID';
export const FETCH_RECOMMEND_COURSES_BY_MAJOR = 'FETCH_RECOMMEND_COURSES_BY_MAJOR';

export const FETCH_COURSES_MENTEES = 'FETCH_COURSES_MENTEES';

export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const TEST_ADD_COURSE = 'TEST_ADD_COURSE';
export const TEST_FETCH_COURSES = 'TEST_FETCH_COURSES';
export const TEST_DELETE_COURSE = 'TEST_DELETE_COURSE';
export const TEST_FETCH_COURSE = 'TEST_FETCH_COURSE';
export const TEST_UPDATE_COURSE = 'TEST_UPDATE_COURSE';

//STUDENT
export const ENROLL_COURSE = 'ENROLL_COURSE';
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE';
export const FETCH_MY_LEARNING_COURSES = 'FETCH_MY_LEARNING_COURSES';
export const ENROLL_CLEAR_STATUS = 'ENROLL_CLEAR_STATUS';


